# Generated by Django 4.0.4 on 2022-04-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
