name: actions
on: [push]
jobs:

  teste:

    runs-on: ubuntu-latest

    #Configurando o Postgres:
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testedb
        ports: [ '5432:5432' ]

    #Steps pro building
    steps:
        - uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v1
          with:
            python-version: 3.9
            architecture: x64

        - name: Instalar Pipenv
          run: |
            pip install pipenv codecov

        - name: Pipenv instalando dependencias
          run: |
            pipenv sync -d
            cp contrib/env-sample .env

        - name: Rodar Testes Automaticos - flake8
          uses: py-actions/flake8@v1

        - name: Rodar Testes Automaticos - Pytest-cov
          run: |
             pipenv run pytest --cov=pypro

        - name: Rodar Relatorio Coverage - codecov
          run: |
             codecov


